// <auto-generated />
namespace HealthService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agedec_to_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agedec_to_int));
        
        string IMigrationMetadata.Id
        {
            get { return "202101040618333_Age(dec_to_int)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
